### ISSUE TITLE
i have a error in this project

### ISSUE THREAD

**Issue by androiddaniel** [iampawan/FlutterWhatsAppClone#16]
Running "flutter pub get" in mesenger...                        
The current Flutter SDK version is 1.9.1+hotfix.6.

Because mesenger depends on camera >=0.5.7+2 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.
pub get failed (1)

**Comment by prasadsunny1** [comment]
Sent a PR #25 to update the project to flutter 1.20.2.
You would be able to build and run after this PR is merged.
@iampawan
