### ISSUE TITLE
error in android manifest

### ISSUE THREAD

**Issue by vinayvishnu725** [iampawan/FlutterWhatsAppClone#20]
uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [:camera] C:\Users\vinay\Desktop\flutterprojects\whats_app\build\camera\intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 16 Suggestion: use a compatible library with a minSdk of at most 16, or increase this project's minSdk version to at least 21, or use tools:overrideLibrary="io.flutter.plugins.camera" to force usage (may lead to runtime failures)

what could be the problem... and also i have changed the minSDKversion... but no changes...

**Comment by skamri** [comment]
unsubscribe me.
