### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by linguanghua** [iampawan/FlutterWhatsAppClone#4]
works on an ANDROID phone.
But crashes when I try to use Camera on iPHONE X.

***in main.dart file:***
>cameras = await availableCameras();

***When I print the cameras.length that result 0.***

***I hope someone can help me.***

>flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following RangeError was thrown building NotificationListener<KeepAliveNotification>:
flutter: RangeError (index): Invalid value: Valid value range is empty: 0
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      List.[] (dart:core/runtime/libgrowable_array.dart:141:60)
flutter: #1      CameraScreenState.initState (package:flutter_what_app/pages/camera_screen.dart:23:44)
flutter: #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3743:58)
flutter: #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #19     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3947:11)
flutter: #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #29     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:744:36)
flutter: #30     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:729:20)
flutter: #31     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2214:19)
flutter: #32     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:722:11)
flutter: #33     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
flutter: #34     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
flutter: #35     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:740:15)
flutter: #36     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
flutter: #37     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
flutter: #38     RenderSliverMultiBoxAdaptor.insertAndLayoutLeadingChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:382:5)
flutter: #39     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:184:31)
flutter: #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #41     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:285:13)
flutter: #42     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1008:12)
flutter: #43     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:932:20)
flutter: #44     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
flutter: #45     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
flutter: #46     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
flutter: #47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
flutter: #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #52     _invoke (dart:ui/hooks.dart:120:13)
flutter: #53     _drawFrame (dart:ui/hooks.dart:109:3)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 215 pos 16: 'indexOf(child) > index': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 215 pos 16: 'indexOf(child) > index': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2218 pos 20: '_debugCurrentBuildTarget == context': is not true.
flutter: Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#9b6a0 NEEDS-LAYOUT NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderErrorBox#cbb6d NEEDS-LAYOUT NEEDS-PAINT

**Comment by SagarPanwala** [comment]
anyone found the solution?
