### ISSUE TITLE
项目运行不了

### ISSUE THREAD

**Issue by YangSmallline** [iampawan/FlutterWhatsAppClone#9]
我现在用的最新的studio和最新的dart flutter sdk ,在github上找的项目都打不开
报错都是这个,我点了packageget update都无反应,麻烦楼主看看

Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  E:\YangChi\githubDownLoad\FlutterApp\lib\official\OfficialNetWorkPage.dart
...refers, in an import, to the following library:
  package:http/http.dart
That library is in a package that is not known. Maybe you forgot to mention it in your pubspec.yaml file?

**Comment by beibeiaiwuhao** [comment]
你这个解决了吗？请问是怎么解决的啊
